name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet -stdmethods=false ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
